---
title: "Análisis exploratorio de datos para odontología"
output: html_notebook
---

# Paquetes
```{r paquetes}
library(tidyverse)
library(tableone)

```

# Importar datos

Convertir a csv e importarlo
```{r read_csv}
df <- read_csv("caries.csv")
```
Importar directamente desde excel
```{r readxls}
df <- readxl::read_xls("caries.xls", sheet = 1)
```

Leer desde un sitio web

```{r read url}
df <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vStv7Pr69DtRKv6Nw6gVBep8hbT3pEeO6B1vNwxK_1DUHgpoTgbuRpZ4SvgtHFQnBZJVGeeQVyRuXZl/pub?gid=1416215037&single=true&output=csv")
```

# Explorar los datos

```{r names}
names(df)
```


```{r estructura}
str(df)
```
## ver datos NA
### Alternativa 1 para ver los NA
```{r}
sum(is.na(df))
```
hay dos datos NA, ¿cuáles?
```{r}
which(is.na(df))
```

```{r}
na.exclude(df)
```

accedemos a esos datos
```{r}
df[4806, ]
```

```{r}
df[5228, ]
```
Los eliminamos

```{r omit.na}
df_clean <- na.omit(df)
```

Ahora comprobamos

```{r}
sum(is.na(df_clean))
```
ok

# Análisis exploratorio de datos
```{r names nuevamente}
names(df_clean)
```

```{r resumen de datos}
summary(df_clean)
```

```{r estructura de datos}
str(df_clean)
```



Convierto variables categoricas

```{r chequeo los nombres}
names(df_clean)
```

```{r convierto a factores}
factores <- c(3, 4, 6, 8, 17, 18 )
df_clean[,factores] <- lapply(df_clean[,factores] , factor)
rm(factores)
str(df_clean)
```
